environment:
  name: cooking_zoo
  env_kwargs:
    num_agents: 2
    recipe_id: "TomatoSalad"  # Start with simple recipe
    max_steps: 200
    obs_spaces: null  # Use default observation spaces
    action_scheme: "scheme1"  # Default action scheme
  apply_wrappers: true

training:
  episodes: 2000
  max_steps_per_episode: 200
  gamma: 0.99
  learning_rate: 3e-4
  epsilon_clip: 0.2
  K_epochs: 8
  c_entropy: 0.02  # Higher entropy for exploration in cooperative tasks
  max_grad_norm: 0.5
  c_value: 0.5
  lam: 0.95
  batch_size: 64
  min_learning_rate: 1e-6
  similarity_loss_coef: 0.2  # Higher for encouraging cooperation

logging:
  log_interval: 10
  save_interval: 100
  eval_interval: 50
  save_best_model: true

model:
  num_heads: 4
  embedding_dim: 256
  hidden_size: 526
  save_dir: "files/Models"
  model_name: "TAAC_cooking_zoo"

# Environment-specific notes:
# - CookingZoo requires coordination between agents
# - Higher similarity_loss_coef encourages cooperation
# - Higher entropy promotes exploration of coordination strategies
# - Recipe_id can be changed: "TomatoSalad", "LettuceWrap", "LobsterPlate", etc. 