environment:
  name: mats_gym
  env_kwargs:
    scenario: "straight"  # Default scenario
    num_agents: 3
    max_episode_steps: 1000
    reward_mech: "global"  # Can be "global", "local", or "mixed"
    render_mode: null
  apply_wrappers: true

training:
  episodes: 2500
  max_steps_per_episode: 1000
  gamma: 0.99
  learning_rate: 2e-4
  epsilon_clip: 0.2
  K_epochs: 8
  c_entropy: 0.02
  max_grad_norm: 0.5
  c_value: 0.5
  lam: 0.95
  batch_size: 96
  min_learning_rate: 1e-6
  similarity_loss_coef: 0.15

logging:
  log_interval: 25
  save_interval: 250
  eval_interval: 100
  save_best_model: true

model:
  num_heads: 6
  embedding_dim: 384
  hidden_size: 768
  save_dir: "files/Models"
  model_name: "TAAC_mats_gym"

# Environment-specific notes:
# - MATS Gym focuses on multi-agent coordination in traffic scenarios
# - Scenario can be changed: "straight", "intersection", "roundabout", etc.
# - Reward mechanism affects cooperation requirements
# - Larger network for complex traffic modeling 